# Generated by Django 4.1.3 on 2022-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_listing_dealer_listing_image_listing_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
