# Generated by Django 4.1.3 on 2022-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_listing_user_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
