# Generated by Django 4.1.3 on 2022-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
