# Generated by Django 4.1.3 on 2022-12-15 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_listing_color_listing_engine_listing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='ReportListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('P', 'Incorrect price'), ('C', 'Incorrect characteristics'), ('F', 'Fake listing'), ('O', 'Other')], max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=50)),
                ('listing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.listing')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
