# Generated by Django 4.1.3 on 2022-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_feedback_comment_reportlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlisting',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='reportlisting',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
