# Generated by Django 4.1.3 on 2022-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_contactform_email_alter_contactform_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
